# NAME: Ruth Johnson
# EMAIL: ruthjohnson@ucla.edu
# ID: 704275412

CC=gcc

default: lab3a.o
	$(CC) -o lab3a lab3a.c 
clean:
	rm lab4b-704275412.tar.gz
	rm lab3a.c
	rm README
	rm Makefile
	rm lab3a.o
	rm lab3a
	ext2_fs.h

dist:
	tar -czvf lab3a-704275412.tar.gz lab3a.c README Makefile ext2_fs.h
